package com.syf;

public enum Code{
	ID,STRING,UNSIGNED_INT,UNSIGNED_FLOAT,MAIN,VOLATILE,STRUCT,TYPEDEF,UNION,AUTO,EXTERN,UNSIGNED,SIGNED,STATIC,SIZEOF,
	CONST,ENUM,CHAR,LONG,FLOAT,DOUBLE,SHORT,INT,DEFAULT,CASE,SWITCH,CONTINUE,BREAK,
	GOTO,ELSE,IF,VOID,RETURN,DO,WHILE,FOR,
	ADD,MINUS,INC,DEC,MULTI,DIV,MOD,MOD_ASSIGN,ADD_ASSGIN,MINUS_ASSIGN,DIV_ASSIGN,MULTI_ASSIGN,EQ,NE,GT,LT,GE,LE,ASSIGN,
	POINTER,L_SHIFT,R_SHIFT,EXP,AND,OR,NOT,ANDAND,OROR,L_BRACKET,R_BRACKET,L_BRACE,R_BRACE,
	SEMIC,COLON,DOT,COMMA
}
